"""initial schema

Revision ID: 04713c9ef6a6
Revises: 
Create Date: 2026-08-11 07:20:17.734202

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04713c9ef6a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('starts_at', sa.String(length=40), nullable=False),
    sa.Column('ends_at', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('applies_to', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.String(length=40), nullable=False),
    sa.Column('ends_at', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_table('conversions',
    sa.Column('click_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('conversion_id', sa.String(length=120), nullable=False),
    sa.Column('external_tx_id', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=False),
    sa.Column('reviewed_at', sa.String(length=40), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_click_id'), 'conversions', ['click_id'], unique=False)
    op.create_index(op.f('ix_conversions_conversion_id'), 'conversions', ['conversion_id'], unique=False)
    op.create_index(op.f('ix_conversions_created_at'), 'conversions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversions_device_id'), 'conversions', ['device_id'], unique=False)
    op.create_index(op.f('ix_conversions_external_tx_id'), 'conversions', ['external_tx_id'], unique=False)
    op.create_index(op.f('ix_conversions_offer_id'), 'conversions', ['offer_id'], unique=False)
    op.create_index(op.f('ix_conversions_provider_id'), 'conversions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_conversions_status'), 'conversions', ['status'], unique=False)
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=False)
    op.create_table('cvx_ledger',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvx_ledger_created_at'), 'cvx_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_cvx_ledger_reference_id'), 'cvx_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_cvx_ledger_transaction_type'), 'cvx_ledger', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_cvx_ledger_user_id'), 'cvx_ledger', ['user_id'], unique=False)
    op.create_table('cvx_rules',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvx_rules_created_at'), 'cvx_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_cvx_rules_key'), 'cvx_rules', ['key'], unique=True)
    op.create_index(op.f('ix_cvx_rules_section'), 'cvx_rules', ['section'], unique=False)
    op.create_table('fraud_events',
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('related_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('handled', sa.String(length=10), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_events_created_at'), 'fraud_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_events_device_id'), 'fraud_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_fraud_events_event_type'), 'fraud_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_fraud_events_ip'), 'fraud_events', ['ip'], unique=False)
    op.create_index(op.f('ix_fraud_events_related_id'), 'fraud_events', ['related_id'], unique=False)
    op.create_index(op.f('ix_fraud_events_severity'), 'fraud_events', ['severity'], unique=False)
    op.create_index(op.f('ix_fraud_events_user_id'), 'fraud_events', ['user_id'], unique=False)
    op.create_table('fraud_rules',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('enabled', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_rules_created_at'), 'fraud_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_rules_key'), 'fraud_rules', ['key'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('countries', sa.Text(), nullable=False),
    sa.Column('devices', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('conversion_event', sa.String(length=80), nullable=False),
    sa.Column('click_url', sa.Text(), nullable=False),
    sa.Column('landing_url', sa.Text(), nullable=False),
    sa.Column('tracking_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_completions', sa.Integer(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('min_user_level', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('revenue_earned', sa.Float(), nullable=False),
    sa.Column('starts_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_category'), 'offers', ['category'], unique=False)
    op.create_index(op.f('ix_offers_created_at'), 'offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_offers_external_id'), 'offers', ['external_id'], unique=False)
    op.create_index(op.f('ix_offers_provider_id'), 'offers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_table('postbacks',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('external_conversion_id', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('signature_valid', sa.String(length=10), nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=False),
    sa.Column('received_at', sa.String(length=40), nullable=False),
    sa.Column('processed', sa.String(length=10), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postbacks_created_at'), 'postbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_postbacks_external_conversion_id'), 'postbacks', ['external_conversion_id'], unique=False)
    op.create_index(op.f('ix_postbacks_provider_id'), 'postbacks', ['provider_id'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('masked', sa.String(length=60), nullable=False),
    sa.Column('rotated_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_credentials_created_at'), 'provider_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_credentials_provider_id'), 'provider_credentials', ['provider_id'], unique=False)
    op.create_table('providers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reward_multiplier', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('revenue_tracked', sa.Float(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_index(op.f('ix_providers_created_at'), 'providers', ['created_at'], unique=False)
    op.create_table('pterodactyl_nodes',
    sa.Column('pterodactyl_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('fqdn', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('memory_allocated', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('disk_allocated', sa.Integer(), nullable=False),
    sa.Column('disk_limit', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pterodactyl_nodes_created_at'), 'pterodactyl_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_pterodactyl_nodes_pterodactyl_id'), 'pterodactyl_nodes', ['pterodactyl_id'], unique=True)
    op.create_index(op.f('ix_pterodactyl_nodes_region'), 'pterodactyl_nodes', ['region'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=False),
    sa.Column('rewarded_at', sa.String(length=40), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('meta', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_invitee_id'), 'referrals', ['invitee_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('regions',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('flag', sa.String(length=4), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_created_at'), 'regions', ['created_at'], unique=False)
    op.create_table('reversals',
    sa.Column('conversion_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('reversed_by', sa.String(length=20), nullable=False),
    sa.Column('credited_back', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reversals_conversion_id'), 'reversals', ['conversion_id'], unique=False)
    op.create_index(op.f('ix_reversals_created_at'), 'reversals', ['created_at'], unique=False)
    op.create_index(op.f('ix_reversals_provider_id'), 'reversals', ['provider_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_table('server_plans',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('disk_mb', sa.Integer(), nullable=False),
    sa.Column('backups', sa.Integer(), nullable=False),
    sa.Column('databases', sa.Integer(), nullable=False),
    sa.Column('allocations', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('egg_id', sa.String(length=36), nullable=False),
    sa.Column('nest_id', sa.String(length=36), nullable=False),
    sa.Column('docker_image', sa.String(length=200), nullable=False),
    sa.Column('startup', sa.Text(), nullable=False),
    sa.Column('cvx_cost', sa.Float(), nullable=False),
    sa.Column('renewal_cost', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_servers_per_user', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_plans_created_at'), 'server_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_server_plans_status'), 'server_plans', ['status'], unique=False)
    op.create_table('server_templates',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('software', sa.String(length=60), nullable=False),
    sa.Column('versions', sa.Text(), nullable=False),
    sa.Column('egg_id', sa.String(length=36), nullable=False),
    sa.Column('nest_id', sa.String(length=36), nullable=False),
    sa.Column('docker_image', sa.String(length=200), nullable=False),
    sa.Column('startup', sa.Text(), nullable=False),
    sa.Column('default_plan_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_templates_created_at'), 'server_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_server_templates_software'), 'server_templates', ['software'], unique=False)
    op.create_table('server_upgrades',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('upgrade_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('cvx_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pterodactyl_job', sa.String(length=120), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_upgrades_created_at'), 'server_upgrades', ['created_at'], unique=False)
    op.create_index(op.f('ix_server_upgrades_server_id'), 'server_upgrades', ['server_id'], unique=False)
    op.create_index(op.f('ix_server_upgrades_status'), 'server_upgrades', ['status'], unique=False)
    op.create_index(op.f('ix_server_upgrades_user_id'), 'server_upgrades', ['user_id'], unique=False)
    op.create_table('servers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('pterodactyl_server_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('egg_id', sa.String(length=36), nullable=False),
    sa.Column('nest_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('disk_mb', sa.Integer(), nullable=False),
    sa.Column('backups', sa.Integer(), nullable=False),
    sa.Column('databases', sa.Integer(), nullable=False),
    sa.Column('allocations', sa.Integer(), nullable=False),
    sa.Column('software', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('last_renewed_at', sa.String(length=40), nullable=False),
    sa.Column('last_activity_at', sa.String(length=40), nullable=False),
    sa.Column('provisioning_error', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_created_at'), 'servers', ['created_at'], unique=False)
    op.create_index(op.f('ix_servers_plan_id'), 'servers', ['plan_id'], unique=False)
    op.create_index(op.f('ix_servers_pterodactyl_server_id'), 'servers', ['pterodactyl_server_id'], unique=True)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_index(op.f('ix_servers_user_id'), 'servers', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_created_at'), 'system_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('public', sa.String(length=5), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_system_settings_section'), 'system_settings', ['section'], unique=False)
    op.create_table('task_clicks',
    sa.Column('click_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_tx_id', sa.String(length=120), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reward_offered', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_clicks_click_id'), 'task_clicks', ['click_id'], unique=True)
    op.create_index(op.f('ix_task_clicks_created_at'), 'task_clicks', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_clicks_device_id'), 'task_clicks', ['device_id'], unique=False)
    op.create_index(op.f('ix_task_clicks_external_tx_id'), 'task_clicks', ['external_tx_id'], unique=False)
    op.create_index(op.f('ix_task_clicks_offer_id'), 'task_clicks', ['offer_id'], unique=False)
    op.create_index(op.f('ix_task_clicks_provider_id'), 'task_clicks', ['provider_id'], unique=False)
    op.create_index(op.f('ix_task_clicks_session_id'), 'task_clicks', ['session_id'], unique=False)
    op.create_index(op.f('ix_task_clicks_status'), 'task_clicks', ['status'], unique=False)
    op.create_index(op.f('ix_task_clicks_user_id'), 'task_clicks', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_created_at'), 'ticket_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_messages_sender_id'), 'ticket_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('upgrade_prices',
    sa.Column('upgrade_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_size', sa.Float(), nullable=False),
    sa.Column('cvx_cost', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_prices_created_at'), 'upgrade_prices', ['created_at'], unique=False)
    op.create_index(op.f('ix_upgrade_prices_upgrade_type'), 'upgrade_prices', ['upgrade_type'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('twofa_enabled', sa.Boolean(), nullable=False),
    sa.Column('twofa_secret', sa.String(length=128), nullable=False),
    sa.Column('backup_codes', sa.String(length=2000), nullable=False),
    sa.Column('last_login_at', sa.String(length=40), nullable=False),
    sa.Column('last_login_ip', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('referral_cvx_earned', sa.Float(), nullable=False),
    sa.Column('cvx_balance', sa.Float(), nullable=False),
    sa.Column('cvx_lifetime_earned', sa.Float(), nullable=False),
    sa.Column('cvx_lifetime_spent', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('conversions_approved', sa.Integer(), nullable=False),
    sa.Column('conversions_pending', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('panel_user_id', sa.String(length=36), nullable=False),
    sa.Column('meta', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_cvx_balance'), 'users', ['cvx_balance'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_risk_score'), 'users', ['risk_score'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_risk_score'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cvx_balance'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upgrade_prices_upgrade_type'), table_name='upgrade_prices')
    op.drop_index(op.f('ix_upgrade_prices_created_at'), table_name='upgrade_prices')
    op.drop_table('upgrade_prices')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_sender_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_created_at'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_task_clicks_user_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_status'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_session_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_provider_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_offer_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_external_tx_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_device_id'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_created_at'), table_name='task_clicks')
    op.drop_index(op.f('ix_task_clicks_click_id'), table_name='task_clicks')
    op.drop_table('task_clicks')
    op.drop_index(op.f('ix_system_settings_section'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_created_at'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_servers_user_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_pterodactyl_server_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_plan_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_created_at'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_server_upgrades_user_id'), table_name='server_upgrades')
    op.drop_index(op.f('ix_server_upgrades_status'), table_name='server_upgrades')
    op.drop_index(op.f('ix_server_upgrades_server_id'), table_name='server_upgrades')
    op.drop_index(op.f('ix_server_upgrades_created_at'), table_name='server_upgrades')
    op.drop_table('server_upgrades')
    op.drop_index(op.f('ix_server_templates_software'), table_name='server_templates')
    op.drop_index(op.f('ix_server_templates_created_at'), table_name='server_templates')
    op.drop_table('server_templates')
    op.drop_index(op.f('ix_server_plans_status'), table_name='server_plans')
    op.drop_index(op.f('ix_server_plans_created_at'), table_name='server_plans')
    op.drop_table('server_plans')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reversals_provider_id'), table_name='reversals')
    op.drop_index(op.f('ix_reversals_created_at'), table_name='reversals')
    op.drop_index(op.f('ix_reversals_conversion_id'), table_name='reversals')
    op.drop_table('reversals')
    op.drop_index(op.f('ix_regions_created_at'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invitee_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_pterodactyl_nodes_region'), table_name='pterodactyl_nodes')
    op.drop_index(op.f('ix_pterodactyl_nodes_pterodactyl_id'), table_name='pterodactyl_nodes')
    op.drop_index(op.f('ix_pterodactyl_nodes_created_at'), table_name='pterodactyl_nodes')
    op.drop_table('pterodactyl_nodes')
    op.drop_index(op.f('ix_providers_created_at'), table_name='providers')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_provider_credentials_provider_id'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_created_at'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_postbacks_provider_id'), table_name='postbacks')
    op.drop_index(op.f('ix_postbacks_external_conversion_id'), table_name='postbacks')
    op.drop_index(op.f('ix_postbacks_created_at'), table_name='postbacks')
    op.drop_table('postbacks')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_provider_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_external_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_created_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_category'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fraud_rules_key'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_created_at'), table_name='fraud_rules')
    op.drop_table('fraud_rules')
    op.drop_index(op.f('ix_fraud_events_user_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_severity'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_related_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_ip'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_event_type'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_device_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_created_at'), table_name='fraud_events')
    op.drop_table('fraud_events')
    op.drop_index(op.f('ix_cvx_rules_section'), table_name='cvx_rules')
    op.drop_index(op.f('ix_cvx_rules_key'), table_name='cvx_rules')
    op.drop_index(op.f('ix_cvx_rules_created_at'), table_name='cvx_rules')
    op.drop_table('cvx_rules')
    op.drop_index(op.f('ix_cvx_ledger_user_id'), table_name='cvx_ledger')
    op.drop_index(op.f('ix_cvx_ledger_transaction_type'), table_name='cvx_ledger')
    op.drop_index(op.f('ix_cvx_ledger_reference_id'), table_name='cvx_ledger')
    op.drop_index(op.f('ix_cvx_ledger_created_at'), table_name='cvx_ledger')
    op.drop_table('cvx_ledger')
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_status'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_provider_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_offer_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_external_tx_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_device_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_created_at'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_conversion_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_click_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
